version: '3.8'
services:
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=shadow-fiend
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=qqqqqq
    volumes:
      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      context: docker/app
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/test
    image: 'redcollar'
    ports:
      - 8080:8080
    depends_on:
      - postgres
volumes:
  db-data: