
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: shadow-fiend
    password: qqqqqq
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
